### PR TITLE
Fix flipping wrong bit for self powered flag.

### PR DESCRIPTION
**Pull request by lnanek**
Fix issue #7 . Using the FTDI D2XX Linux EEPROM write example I set the self powered flag to off and on and noticed the ninth byte of the EEPROM changed from a0 to e0, which corresponds to or'ing in a 40 instead of a 20 like the ftx_prog program was doing. Confirmed the read example reads out the same as what is specified with ftx_prog for that field now. Haven't checked any of the other fields yet, though, like remote wakeup and PnP.

### CODE REVIEW

**Comment by lnanek** [comment]
Confirmed remote wakeup option on/off wasn't showing up in the FTDI D2XX Linux EEPROM read example either until changed.

**Comment by lnanek** [comment]
Closing PR since people started making unrelated changes on the branch.

**Comment by richardeoin** [comment]
@lnanek Please create another PR with just your changes if you can. This looks like a useful fix.

**Comment by lnanek** [comment]
Here you go:
https://github.com/richardeoin/ftx-prog/pull/9

Thanks for the utility. For some reason the official FTDI D2XX EEPROM write examples refused to write newer fields like the CBUS ones, and when we contacted them they said it hadn't been updated to support the new X series yet. So we were basically told only the Windows tool would work until we found this.

**Pull request closed without merging**
